Repository CCOMS-UAM/yos-award, pull requests merged in 2022-12, with the labels that each got.

#1 Template setup
  .Rprofile
  R/.gitignore
  README.md
  dat/.gitignore
  notebooks/.gitignore
  output/Form.md
  renv.lock
  renv/.gitignore
  renv/activate.R
  rstudio_project.Rproj
  src/.gitignore
Labels: accepted, drafting, feature

#8 Fills-in reusability section
  output/Form.md
Labels: accepted, drafting, feature, help wanted

#6 Fills in follow-up section
  output/Form.md
Labels: accepted, drafting, feature

#7 Fills in "Description" section
  output/Form.md
Labels: accepted, feature, output

#10 Merges minutes of 16-12-2022 meeting
  doc/minutes/2022-12-16.md
Labels: accepted, documentation, feature
